package gemini

import (
	"context"
	"fmt"

	"github.com/google/generative-ai-go/genai"
	"google.golang.org/api/option"
)

// Client wraps the Google Gemini API client
type Client struct {
	apiKey string
	model  string
}

// NewClient creates a new Gemini client
// model defaults to "gemini-3-flash-preview" if not specified
func NewClient(apiKey string, model string) (*Client, error) {
	if apiKey == "" {
		return nil, fmt.Errorf("Gemini API key is required")
	}

	if model == "" {
		model = "gemini-3-flash-preview"
	}

	return &Client{
		apiKey: apiKey,
		model:  model,
	}, nil
}

// GenerateReleaseNote uses Gemini to generate a release note based on PR context
func (c *Client) GenerateReleaseNote(ctx context.Context, prContext PRContext) (string, error) {
	// Create Gemini client
	client, err := genai.NewClient(ctx, option.WithAPIKey(c.apiKey))
	if err != nil {
		return "", fmt.Errorf("failed to create Gemini client: %w", err)
	}
	defer client.Close()

	// Get the model
	model := client.GenerativeModel(c.model)

	// Build the prompt
	prompt := buildReleaseNotePrompt(prContext)

	// Generate content
	resp, err := model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("Gemini API call failed: %w", err)
	}

	// Extract text from response
	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no content generated by Gemini")
	}

	// Get the first part as text
	result := ""
	for _, part := range resp.Candidates[0].Content.Parts {
		if txt, ok := part.(genai.Text); ok {
			result += string(txt)
		}
	}

	return result, nil
}
